name: (beta) release for every commit

on:
  workflow_dispatch:
    inputs:
      base_ref:
        description: Base branch, tag, or commit
        required: false
        default: main
  push:

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.base_ref || github.ref }}

      - name: Setup MSVC
        if: matrix.os == 'windows-latest'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug

      - name: Build
        run: cmake --build build

      - name: Install
        run: cmake --install build --prefix publish --config Debug

      - name: Zip artifacts
        shell: bash
        run: |
          if [ "$RUNNER_OS" = "Windows" ]; then
            powershell Compress-Archive -Path publish\* -DestinationPath build-${{ runner.os }}.zip
          else
            zip -r build-${{ runner.os }}.zip publish
          fi

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ github.sha }}
          name: build-${{ github.sha }}
          files: build-${{ runner.os }}-x86_64.zip
