name: (beta) release for every commit

on:
  workflow_dispatch:
    inputs:
      base_ref:
        description: "Base branch, tag, or commit"
        required: false
        default: "main"
  push:

permissions:
  contents: write
jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.base_ref || github.ref }}
      - uses: ilammy/msvc-dev-cmd@v1
      - name: BUILD
        run: |
          mkdir build
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl
          cmake --build build
      - name: publish
        run: |
          cmake --install build --prefix "publish" --config Debug
          powershell Compress-Archive -Path publish\* -DestinationPath build.zip
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ github.sha }}
          name: build-${{ github.sha }}
          files: build.zip
